#!/usr/bin/env python3
"""
Taxonomy Dashboard Generator

Generates an interactive HTML dashboard from taxonomy statistics JSON data.

Usage:
    python taxonomy_html.py

Input:
    - webapp/taxonomy_stats.json (generated by generate_taxonomy_stats.py)

Output:
    - webapp/taxonomy_dashboard.html (interactive dashboard)

Dashboard Features:
    - Statistics overview (total, zoonotic, non-zoonotic counts)
    - Sequence length statistics
    - Taxonomy distribution (pie charts for each rank)
    - Host distribution (top 15 non-human hosts)
    - Data source distribution
    - Geographic distribution (top 15 countries)

Requirements:
    - echarts (for pie charts)
    - tailwindcss (for styling)
    - Inter font

Notes:
    - Called automatically by generate_taxonomy_stats.py
    - Generates single HTML file with embedded CSS/JS
    - Responsive design with dark theme
"""

import json
import os

def generate_dashboard():
    stats_file  = 'webapp/taxonomy_stats.json'
    output_file = 'webapp/taxonomy_dashboard.html'
    
    with open(stats_file, 'r') as f:
        stats = json.load(f)
    
    stats_json = json.dumps(stats)
    
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Taxonomy Dashboard - VirSeNtAI</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.4.3/echarts.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root {{
            --bg-dark: #111518;
            --border-dark: #2d363d;
            --accent-red: #ff0000;
            --accent-cyan: #00bcd4;
            --text-faded: #9cabba;
            --text-strong: white;
            --card-bg-dark: #1b2127;
        }}
        body {{
            font-family: 'Inter', sans-serif;
            background-color: var(--bg-dark);
            min-height: 100vh;
        }}
        .glass-card {{
            background: var(--card-bg-dark);
            border: 1px solid var(--border-dark);
            border-radius: 0.75rem;
        }}
        .chart-container {{
            height: 500px;
            position: relative;
        }}
        .stat-card:hover {{
            transform: translateY(-2px);
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.3);
        }}
    </style>
</head>
<body>
    <header class="flex items-center justify-between whitespace-nowrap border-b border-solid border-b-[#2d363d] px-10 py-3">
        <div class="flex items-center gap-8">
            <div class="flex items-center gap-4 text-white">
                <span class="text-[#ff0000] text-xl font-extrabold leading-none">></span>
                <h2 class="text-white text-lg font-bold leading-tight tracking-[-0.015em]">virsentai</h2>
            </div>
            <div class="flex items-center gap-9">
                <a class="text-[#9cabba] text-sm font-medium leading-normal" href="./index.html">Overview</a>
                <a class="text-[#9cabba] text-sm font-medium leading-normal" href="./repurposing.html">Drug Repurposing</a>
                <a class="text-[#ff0000] text-sm font-bold leading-normal" href="#">Dataset Taxonomy</a>
                <a class="text-[#9cabba] text-sm font-medium leading-normal" href="./models.html">Models</a>
                <a class="text-[#9cabba] text-sm font-medium leading-normal" href="./about.html">About</a>
            </div>
        </div>
    </header>

    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div class="text-center mb-8">
            <h1 class="text-white tracking-light text-[32px] font-bold leading-tight mb-2">Training Dataset Taxonomy Analysis</h1>
            <p class="text-[#9cabba] text-base">Comprehensive breakdown of the balanced dataset used to train VirSeNtAI</p>
        </div>

        <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4 mb-8">
            <div class="stat-card glass-card rounded-xl p-4 text-center">
                <div class="text-2xl font-bold text-white" id="stat-total">0</div>
                <div class="text-xs text-[#9cabba] uppercase tracking-wide">Total Sequences</div>
            </div>
            <div class="stat-card glass-card rounded-xl p-4 text-center">
                <div class="text-2xl font-bold text-[#00bcd4]" id="stat-zoonotic">0</div>
                <div class="text-xs text-[#9cabba] uppercase tracking-wide">Zoonotic (label=1)</div>
            </div>
            <div class="stat-card glass-card rounded-xl p-4 text-center">
                <div class="text-2xl font-bold text-[#ff0000]" id="stat-non-zoonotic">0</div>
                <div class="text-xs text-[#9cabba] uppercase tracking-wide">Non-Zoonotic (label=0)</div>
            </div>
            <div class="stat-card glass-card rounded-xl p-4 text-center">
                <div class="text-2xl font-bold text-white" id="stat-sources">0</div>
                <div class="text-xs text-[#9cabba] uppercase tracking-wide">Data Sources</div>
            </div>
            <div class="stat-card glass-card rounded-xl p-4 text-center">
                <div class="text-2xl font-bold text-white" id="stat-species">0</div>
                <div class="text-xs text-[#9cabba] uppercase tracking-wide">Unique Species</div>
            </div>
        </div>

        <div class="glass-card rounded-xl p-4 mb-8">
            <div class="grid grid-cols-4 gap-4 text-center">
                <div>
                    <div class="text-xl font-bold text-white" id="length-min">0</div>
                    <div class="text-xs text-[#9cabba]">Min Length</div>
                </div>
                <div>
                    <div class="text-xl font-bold text-white" id="length-max">0</div>
                    <div class="text-xs text-[#9cabba]">Max Length</div>
                </div>
                <div>
                    <div class="text-xl font-bold text-white" id="length-mean">0</div>
                    <div class="text-xs text-[#9cabba]">Mean Length</div>
                </div>
                <div>
                    <div class="text-xl font-bold text-white" id="length-median">0</div>
                    <div class="text-xs text-[#9cabba]">Median Length</div>
                </div>
            </div>
        </div>

        <div class="mb-8">
            <h2 class="text-white font-semibold text-lg mb-4">Realm Distribution</h2>
            <div class="glass-card rounded-xl p-4">
                <div id="chart-realm" class="chart-container"></div>
            </div>
        </div>

        <div class="mb-8">
            <h2 class="text-white font-semibold text-lg mb-4">Kingdom Distribution</h2>
            <div class="glass-card rounded-xl p-4">
                <div id="chart-kingdom" class="chart-container"></div>
            </div>
        </div>

        <div class="mb-8">
            <h2 class="text-white font-semibold text-lg mb-4">Phylum Distribution</h2>
            <div class="glass-card rounded-xl p-4">
                <div id="chart-phylum" class="chart-container"></div>
            </div>
        </div>

        <div class="mb-8">
            <h2 class="text-white font-semibold text-lg mb-4">Class Distribution</h2>
            <div class="glass-card rounded-xl p-4">
                <div id="chart-class" class="chart-container"></div>
            </div>
        </div>

        <div class="mb-8">
            <h2 class="text-white font-semibold text-lg mb-4">Order Distribution</h2>
            <div class="glass-card rounded-xl p-4">
                <div id="chart-order" class="chart-container"></div>
            </div>
        </div>

        <div class="mb-8">
            <h2 class="text-white font-semibold text-lg mb-4">Family Distribution</h2>
            <div class="glass-card rounded-xl p-4">
                <div id="chart-family" class="chart-container"></div>
            </div>
        </div>

        <div class="mb-8">
            <h2 class="text-white font-semibold text-lg mb-4">Genus Distribution</h2>
            <div class="glass-card rounded-xl p-4">
                <div id="chart-genus" class="chart-container"></div>
            </div>
        </div>

        <div class="mb-8">
            <h2 class="text-white font-semibold text-lg mb-4">Species Distribution</h2>
            <div class="glass-card rounded-xl p-4">
                <div id="chart-species" class="chart-container"></div>
            </div>
        </div>

        <div class="mb-8">
            <h2 class="text-white font-semibold text-lg mb-4">Non-human Host Distribution</h2>
            <div class="glass-card rounded-xl p-4">
                <div id="chart-host" class="chart-container"></div>
            </div>
        </div>

        <div class="mb-8">
            <h2 class="text-white font-semibold text-lg mb-4">Data Source Distribution</h2>
            <div class="glass-card rounded-xl p-4">
                <div id="chart-source" class="chart-container"></div>
            </div>
        </div>

        <div class="mb-8">
            <h2 class="text-white font-semibold text-lg mb-4">Geographic Distribution</h2>
            <div class="glass-card rounded-xl p-4">
                <h3 class="text-white font-semibold mb-3">Top 15 Countries</h3>
                <div id="chart-country" class="chart-container"></div>
            </div>
        </div>
    </main>

    <footer class="text-center text-[#9cabba] py-8 mt-8">
        <div class="max-w-7xl mx-auto px-4 text-center">
            <p>© 2025 Copyright by <a href="https://rnasa-imedir.udc.es/en/" class="text-white hover:text-[#ff0000]">RNASA</a>, <a href="https://citic.udc.es/en/home-english-2/" class="text-white hover:text-[#ff0000]">CITIC</a>, <a href="https://www.udc.es/en/" class="text-white hover:text-[#ff0000]">UDC</a>, Spain</p>
        </div>
    </footer>

    <script>
        const STATS = {stats_json};

        function formatNumber(num) {{
            return num.toString().replace(/\\B(?=(\\d{{3}})+(?!\\d))/g, ",");
        }}

        function createHorizontalBarChart(elementId, data, title) {{
            const chart = echarts.init(document.getElementById(elementId));
            const sorted = Object.entries(data).sort((a, b) => b[1] - a[1]).slice(0, 10);
            
            const option = {{
                backgroundColor: 'transparent',
                tooltip: {{
                    trigger: 'axis',
                    axisPointer: {{ type: 'shadow' }},
                    backgroundColor: 'rgba(0,0,0,0.7)',
                    textStyle: {{ color: '#fff' }}
                }},
                grid: {{ left: '3%', right: '10%', bottom: '3%', top: '3%', containLabel: true }},
                xAxis: {{
                    type: 'value',
                    axisLabel: {{ color: '#9cabba', fontSize: 10 }},
                    splitLine: {{ lineStyle: {{ color: '#2d363d' }} }}
                }},
                yAxis: {{
                    type: 'category',
                    data: sorted.map(([name]) => name.length > 25 ? name.substring(0, 25) + '...' : name).reverse(),
                    axisLabel: {{ color: '#9cabba', fontSize: 10 }},
                    axisLine: {{ lineStyle: {{ color: '#2d363d' }} }}
                }},
                series: [{{
                    type: 'bar',
                    data: sorted.map(([, value]) => value).reverse(),
                    itemStyle: {{
                        color: new echarts.graphic.LinearGradient(0, 0, 1, 0, [
                            {{ offset: 0, color: '#ff0000' }},
                            {{ offset: 1, color: '#ff6666' }}
                        ]),
                        borderRadius: [0, 4, 4, 0]
                    }},
                    barWidth: '60%'
                }}]
            }};
            chart.setOption(option);
            return chart;
        }}

        function createPieChart(elementId, data, title) {{
            const chart = echarts.init(document.getElementById(elementId));
            const sorted = Object.entries(data).sort((a, b) => b[1] - a[1]);
            const total = sorted.reduce((sum, [, v]) => sum + v, 0);
            const topItems = sorted.slice(0, 12);
            const othersValue = sorted.slice(12).reduce((sum, [, v]) => sum + v, 0);
            
            let pieData = topItems.map(([name, value]) => ({{ 
                name: name.length > 30 ? name.substring(0, 30) + '...' : name, 
                value 
            }}));
            
            if (othersValue > 0) {{
                pieData.push({{ name: 'Others', value: othersValue }});
            }}
            
            const colors = [
                '#ff0000', '#00bcd4', '#ff6666', '#00e5cc', '#ff3333', '#4dd0e1',
                '#cc0000', '#80deea', '#ff9999', '#b2ebf2', '#ffcccc', '#e0f7fa',
                '#666666'
            ];
            
            const option = {{
                backgroundColor: 'transparent',
                tooltip: {{
                    trigger: 'item',
                    backgroundColor: 'rgba(0,0,0,0.8)',
                    textStyle: {{ color: '#fff', fontSize: 12 }},
                    formatter: function(params) {{
                        const pct = ((params.value / total) * 100).toFixed(1);
                        return `<b>${{params.name}}</b><br/>Count: ${{params.value}}<br/>Percentage: ${{pct}}%`;
                    }}
                }},
                legend: {{
                    show: true,
                    orient: 'vertical',
                    right: '5%',
                    top: 'center',
                    textStyle: {{ color: '#9cabba', fontSize: 11 }},
                    itemWidth: 12,
                    itemHeight: 12,
                    itemGap: 8
                }},
                series: [{{
                    type: 'pie',
                    radius: ['25%', '60%'],
                    center: ['40%', '50%'],
                    avoidLabelOverlap: true,
                    data: pieData,
                    label: {{
                        show: true,
                        position: 'outside',
                        color: '#9cabba',
                        fontSize: 11,
                        formatter: '{{b}}: {{c}}'
                    }},
                    itemStyle: {{
                        borderRadius: 4,
                        borderColor: '#111518',
                        borderWidth: 1
                    }},
                    emphasis: {{
                        itemStyle: {{
                            shadowBlur: 10,
                            shadowOffsetX: 0,
                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                        }},
                        label: {{
                            show: true,
                            fontSize: 12,
                            fontWeight: 'bold',
                            color: '#fff',
                            formatter: '{{b}}: {{c}} ({{d}}%)'
                        }}
                    }},
                    labelLine: {{
                        show: true,
                        lineStyle: {{ color: '#9cabba' }}
                    }},
                    labelLine: {{
                        show: false
                    }}
                }}]
            }};
            chart.setOption(option);
            return chart;
        }}

        const charts = [];

        function initCharts() {{
            charts.push(createPieChart('chart-realm', STATS.taxonomy_counts.realm, 'Realm'));
            charts.push(createPieChart('chart-kingdom', STATS.taxonomy_counts.kingdom, 'Kingdom'));
            charts.push(createPieChart('chart-phylum', STATS.taxonomy_counts.phylum, 'Phylum'));
            charts.push(createPieChart('chart-class', STATS.taxonomy_counts['class'], 'Class'));
            charts.push(createPieChart('chart-order', STATS.taxonomy_counts.order, 'Order'));
            charts.push(createPieChart('chart-family', STATS.taxonomy_counts.family, 'Family'));
            charts.push(createPieChart('chart-genus', STATS.taxonomy_counts.genus, 'Genus'));
            charts.push(createPieChart('chart-species', STATS.taxonomy_counts.species, 'Species'));
            const nonHumanHosts = Object.fromEntries(
                Object.entries(STATS.host_counts)
                    .filter(([key]) => key.toLowerCase() !== 'homo sapiens')
                    .sort((a, b) => b[1] - a[1])
            );
            charts.push(createPieChart('chart-host', nonHumanHosts, 'Non-Human Host'));
            charts.push(createPieChart('chart-source', STATS.source_counts, 'Source'));
            charts.push(createHorizontalBarChart('chart-country', STATS.country_counts, 'Country'));
        }}

        function updateStats() {{
            document.getElementById('stat-total').textContent = formatNumber(STATS.total);
            document.getElementById('stat-zoonotic').textContent = formatNumber(STATS.zoonotic);
            document.getElementById('stat-non-zoonotic').textContent = formatNumber(STATS.non_zoonotic);
            document.getElementById('stat-sources').textContent = Object.keys(STATS.source_counts).length;
            document.getElementById('stat-species').textContent = formatNumber(STATS.unique_species);
            document.getElementById('length-max').textContent = formatNumber(STATS.length_stats.max);
            document.getElementById('length-min').textContent = formatNumber(STATS.length_stats.min);
            document.getElementById('length-mean').textContent = formatNumber(Math.round(STATS.length_stats.mean));
            document.getElementById('length-median').textContent = formatNumber(Math.round(STATS.length_stats.median));
        }}

        window.addEventListener('resize', () => {{
            charts.forEach(chart => chart && chart.resize());
        }});

        document.addEventListener('DOMContentLoaded', () => {{
            updateStats();
            initCharts();
        }});
    </script>
</body>
</html>'''

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html)
    
    print(f"Dashboard generated: {output_file}")

if __name__ == "__main__":
    generate_dashboard()